<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'country_code' => '93'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'country_code' => '355'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'country_code' => '213'],
            ['name' => 'American Samoa', 'iso_code' => 'AS', 'country_code' => '1684'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'country_code' => '376'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'country_code' => '244'],
            ['name' => 'Anguilla', 'iso_code' => 'AI', 'country_code' => '1264'],
            ['name' => 'Antarctica', 'iso_code' => 'AQ', 'country_code' => '672'],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'AG', 'country_code' => '1268'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'country_code' => '54'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'country_code' => '374'],
            ['name' => 'Aruba', 'iso_code' => 'AW', 'country_code' => '297'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'country_code' => '61'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'country_code' => '43'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'country_code' => '994'],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'country_code' => '1242'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'country_code' => '973'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'country_code' => '880'],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'country_code' => '1246'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'country_code' => '375'],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'country_code' => '32'],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'country_code' => '501'],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'country_code' => '229'],
            ['name' => 'Bermuda', 'iso_code' => 'BM', 'country_code' => '1441'],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'country_code' => '975'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'country_code' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'country_code' => '387'],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'country_code' => '267'],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'country_code' => '55'],
            ['name' => 'British Indian Ocean Territory', 'iso_code' => 'IO', 'country_code' => '246'],
            ['name' => 'British Virgin Islands', 'iso_code' => 'VG', 'country_code' => '1284'],
            ['name' => 'Brunei', 'iso_code' => 'BN', 'country_code' => '673'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'country_code' => '359'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'country_code' => '226'],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'country_code' => '257'],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'country_code' => '855'],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'country_code' => '237'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'country_code' => '1'],
            ['name' => 'Cape Verde', 'iso_code' => 'CV', 'country_code' => '238'],
            ['name' => 'Cayman Islands', 'iso_code' => 'KY', 'country_code' => '1345'],
            ['name' => 'Central African Republic', 'iso_code' => 'CF', 'country_code' => '236'],
            ['name' => 'Chad', 'iso_code' => 'TD', 'country_code' => '235'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'country_code' => '56'],
            ['name' => 'China', 'iso_code' => 'CN', 'country_code' => '86'],
            ['name' => 'Christmas Island', 'iso_code' => 'CX', 'country_code' => '61'],
            ['name' => 'Cocos Islands', 'iso_code' => 'CC', 'country_code' => '61'],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'country_code' => '57'],
            ['name' => 'Comoros', 'iso_code' => 'KM', 'country_code' => '269'],
            ['name' => 'Cook Islands', 'iso_code' => 'CK', 'country_code' => '682'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'country_code' => '506'],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'country_code' => '385'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'country_code' => '53'],
            ['name' => 'Curacao', 'iso_code' => 'CW', 'country_code' => '599'],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'country_code' => '357'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'country_code' => '420'],
            ['name' => 'Democratic Republic of the Congo', 'iso_code' => 'CD', 'country_code' => '243'],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'country_code' => '45'],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'country_code' => '253'],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'country_code' => '1767'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'country_code' => '1809'],
            ['name' => 'East Timor', 'iso_code' => 'TL', 'country_code' => '670'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'country_code' => '593'],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'country_code' => '20'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'country_code' => '503'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GQ', 'country_code' => '240'],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'country_code' => '291'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'country_code' => '372'],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'country_code' => '251'],
            ['name' => 'Falkland Islands', 'iso_code' => 'FK', 'country_code' => '500'],
            ['name' => 'Faroe Islands', 'iso_code' => 'FO', 'country_code' => '298'],
            ['name' => 'Fiji', 'iso_code' => 'FJ', 'country_code' => '679'],
            ['name' => 'Finland', 'iso_code' => 'FI', 'country_code' => '358'],
            ['name' => 'France', 'iso_code' => 'FR', 'country_code' => '33'],
            ['name' => 'French Polynesia', 'iso_code' => 'PF', 'country_code' => '689'],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'country_code' => '241'],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'country_code' => '220'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'country_code' => '995'],
            ['name' => 'Germany', 'iso_code' => 'DE', 'country_code' => '49'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'country_code' => '233'],
            ['name' => 'Gibraltar', 'iso_code' => 'GI', 'country_code' => '350'],
            ['name' => 'Greece', 'iso_code' => 'GR', 'country_code' => '30'],
            ['name' => 'Greenland', 'iso_code' => 'GL', 'country_code' => '299'],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'country_code' => '1473'],
            ['name' => 'Guam', 'iso_code' => 'GU', 'country_code' => '1671'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'country_code' => '502'],
            ['name' => 'Guernsey', 'iso_code' => 'GG', 'country_code' => '44'],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'country_code' => '224'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GW', 'country_code' => '245'],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'country_code' => '592'],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'country_code' => '509'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'country_code' => '504'],
            ['name' => 'Hong Kong', 'iso_code' => 'HK', 'country_code' => '852'],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'country_code' => '36'],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'country_code' => '354'],
            ['name' => 'India', 'iso_code' => 'IN', 'country_code' => '91'],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'country_code' => '62'],
            ['name' => 'Iran', 'iso_code' => 'IR', 'country_code' => '98'],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'country_code' => '964'],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'country_code' => '353'],
            ['name' => 'Isle of Man', 'iso_code' => 'IM', 'country_code' => '44'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'country_code' => '972'],
            ['name' => 'Italy', 'iso_code' => 'IT', 'country_code' => '39'],
            ['name' => 'Ivory Coast', 'iso_code' => 'CI', 'country_code' => '225'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'country_code' => '1876'],
            ['name' => 'Japan', 'iso_code' => 'JP', 'country_code' => '81'],
            ['name' => 'Jersey', 'iso_code' => 'JE', 'country_code' => '44'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'country_code' => '962'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'country_code' => '7'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'country_code' => '254'],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'country_code' => '686'],
            ['name' => 'Kosovo', 'iso_code' => 'XK', 'country_code' => '383'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'country_code' => '965'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'country_code' => '996'],
            ['name' => 'Laos', 'iso_code' => 'LA', 'country_code' => '856'],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'country_code' => '371'],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'country_code' => '961'],
            ['name' => 'Lesotho', 'iso_code' => 'LS', 'country_code' => '266'],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'country_code' => '231'],
            ['name' => 'Libya', 'iso_code' => 'LY', 'country_code' => '218'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'country_code' => '423'],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'country_code' => '370'],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'country_code' => '352'],
            ['name' => 'Macau', 'iso_code' => 'MO', 'country_code' => '853'],
            ['name' => 'Macedonia', 'iso_code' => 'MK', 'country_code' => '389'],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'country_code' => '261'],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'country_code' => '265'],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'country_code' => '60'],
            ['name' => 'Maldives', 'iso_code' => 'MV', 'country_code' => '960'],
            ['name' => 'Mali', 'iso_code' => 'ML', 'country_code' => '223'],
            ['name' => 'Malta', 'iso_code' => 'MT', 'country_code' => '356'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MH', 'country_code' => '692'],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'country_code' => '222'],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'country_code' => '230'],
            ['name' => 'Mayotte', 'iso_code' => 'YT', 'country_code' => '262'],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'country_code' => '52'],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'country_code' => '691'],
            ['name' => 'Moldova', 'iso_code' => 'MD', 'country_code' => '373'],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'country_code' => '377'],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'country_code' => '976'],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'country_code' => '382'],
            ['name' => 'Montserrat', 'iso_code' => 'MS', 'country_code' => '1664'],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'country_code' => '212'],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'country_code' => '258'],
            ['name' => 'Myanmar', 'iso_code' => 'MM', 'country_code' => '95'],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'country_code' => '264'],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'country_code' => '674'],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'country_code' => '977'],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'country_code' => '31'],
            ['name' => 'Netherlands Antilles', 'iso_code' => 'AN', 'country_code' => '599'],
            ['name' => 'New Caledonia', 'iso_code' => 'NC', 'country_code' => '687'],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'country_code' => '64'],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'country_code' => '505'],
            ['name' => 'Niger', 'iso_code' => 'NE', 'country_code' => '227'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'country_code' => '234'],
            ['name' => 'Niue', 'iso_code' => 'NU', 'country_code' => '683'],
            ['name' => 'North Korea', 'iso_code' => 'KP', 'country_code' => '850'],
            ['name' => 'Northern Mariana Islands', 'iso_code' => 'MP', 'country_code' => '1670'],
            ['name' => 'Norway', 'iso_code' => 'NO', 'country_code' => '47'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'country_code' => '968'],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'country_code' => '92'],
            ['name' => 'Palau', 'iso_code' => 'PW', 'country_code' => '680'],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'country_code' => '970'],
            ['name' => 'Panama', 'iso_code' => 'PA', 'country_code' => '507'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PG', 'country_code' => '675'],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'country_code' => '595'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'country_code' => '51'],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'country_code' => '63'],
            ['name' => 'Pitcairn', 'iso_code' => 'PN', 'country_code' => '64'],
            ['name' => 'Poland', 'iso_code' => 'PL', 'country_code' => '48'],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'country_code' => '351'],
            ['name' => 'Puerto Rico', 'iso_code' => 'PR', 'country_code' => '1787'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'country_code' => '974'],
            ['name' => 'Republic of the Congo', 'iso_code' => 'CG', 'country_code' => '242'],
            ['name' => 'Reunion', 'iso_code' => 'RE', 'country_code' => '262'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'country_code' => '40'],
            ['name' => 'Russia', 'iso_code' => 'RU', 'country_code' => '7'],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'country_code' => '250'],
            ['name' => 'Saint Barthelemy', 'iso_code' => 'BL', 'country_code' => '590'],
            ['name' => 'Saint Helena', 'iso_code' => 'SH', 'country_code' => '290'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN', 'country_code' => '1869'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LC', 'country_code' => '1758'],
            ['name' => 'Saint Martin', 'iso_code' => 'MF', 'country_code' => '590'],
            ['name' => 'Saint Pierre and Miquelon', 'iso_code' => 'PM', 'country_code' => '508'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC', 'country_code' => '1784'],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'country_code' => '685'],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'country_code' => '378'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'ST', 'country_code' => '239'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'country_code' => '966'],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'country_code' => '221'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'country_code' => '381'],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'country_code' => '248'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'country_code' => '232'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'country_code' => '65'],
            ['name' => 'Sint Maarten', 'iso_code' => 'SX', 'country_code' => '1721'],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'country_code' => '421'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'country_code' => '386'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'country_code' => '677'],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'country_code' => '252'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'country_code' => '27'],
            ['name' => 'South Korea', 'iso_code' => 'KR', 'country_code' => '82'],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'country_code' => '211'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'country_code' => '34'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'country_code' => '94'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'country_code' => '249'],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'country_code' => '597'],
            ['name' => 'Svalbard and Jan Mayen', 'iso_code' => 'SJ', 'country_code' => '47'],
            ['name' => 'Swaziland', 'iso_code' => 'SZ', 'country_code' => '268'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'country_code' => '46'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'country_code' => '41'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'country_code' => '963'],
            ['name' => 'Taiwan', 'iso_code' => 'TW', 'country_code' => '886'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'country_code' => '992'],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'country_code' => '255'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'country_code' => '66'],
            ['name' => 'Togo', 'iso_code' => 'TG', 'country_code' => '228'],
            ['name' => 'Tokelau', 'iso_code' => 'TK', 'country_code' => '690'],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'country_code' => '676'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'country_code' => '1868'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'country_code' => '216'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'country_code' => '90'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'country_code' => '993'],
            ['name' => 'Turks and Caicos Islands', 'iso_code' => 'TC', 'country_code' => '1649'],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'country_code' => '688'],
            ['name' => 'U.S. Virgin Islands', 'iso_code' => 'VI', 'country_code' => '1340'],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'country_code' => '256'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'country_code' => '380'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'country_code' => '971'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'country_code' => '44'],
            ['name' => 'United States', 'iso_code' => 'US', 'country_code' => '1'],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'country_code' => '598'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'country_code' => '998'],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'country_code' => '678'],
            ['name' => 'Vatican', 'iso_code' => 'VA', 'country_code' => '379'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'country_code' => '58'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'country_code' => '84'],
            ['name' => 'Wallis and Futuna', 'iso_code' => 'WF', 'country_code' => '681'],
            ['name' => 'Western Sahara', 'iso_code' => 'EH', 'country_code' => '212'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'country_code' => '967'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'country_code' => '260'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'country_code' => '263'],
        ];

        DB::table('countries')->insert($countries);
    }
}
